name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-and-test:
    name: Run on ${{ matrix.os }} with SOFA ${{ matrix.sofa_branch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]  
        sofa_branch: [master]

    steps:
      - name: (Mac) Workaround for homebrew
        shell: bash
        if: runner.os == 'macOS'
        run: |
            rm -f /usr/local/bin/2to3
            rm -f /usr/local/bin/idle3
            rm -f /usr/local/bin/pydoc3
            rm -f /usr/local/bin/python3
            rm -f /usr/local/bin/python3-config
            rm -f /usr/local/bin/2to3-3.11
            rm -f /usr/local/bin/idle3.11
            rm -f /usr/local/bin/pydoc3.11
            rm -f /usr/local/bin/python3.11
            rm -f /usr/local/bin/python3.11-config

      - name: Setup SOFA and environment
        id: sofa
        uses: sofa-framework/sofa-setup-action@v4
        with:
          sofa_root: ${{ github.workspace }}/sofa
          sofa_version: ${{ matrix.sofa_branch }}
          sofa_scope: 'standard'

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_SRC_PATH }}

      - name: Scenes tests
        shell: bash
        run: |
          cd "$WORKSPACE_SRC_PATH"
          echo "$SOFA_ROOT"
          ls -la "$SOFA_ROOT"
          for f in $(find ./doc/examples -type f -name "*.py" | xargs grep -r "createScene" | cut -d':' -f1 | uniq); do
            echo "Testing $f..."
          done
          
